<a href="https://colab.research.google.com/github/DeltaINKDesign/Keras/blob/master/Izabela_Michalak_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 1. Zaimportuj bibliotekę numpy z aliasem `np` 

In [0]:
import numpy as np

#### 2. Przypisz do zmiennej x, wektor o rozmiarze 10, wypełniony zerami

In [0]:
x = np.zeros(10)

#### 3. Zmień piąty element wektora x, tak by jego wartość wynosiła 1

In [3]:
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 4.  Stwórz wektor którego pierwszy element wynosi 3, a ostatni 345. Każdy kolejny element jest o jeden większy od poprzedniego.

In [4]:
y = np.arange(3,345)
y

array([  3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
        16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
        29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
        42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,
        55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,
        68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,
        81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
        94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106,
       107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119,
       120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
       133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145,
       146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158,
       159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171,
       172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 18

#### 5.  Stwórz macierz 3x3 z wartościami od 0 do 9.

In [5]:
z = np.arange(9)
z = z.reshape(3,3)
z


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 6. Znajdź indeksy niezerowych elementów listy \[1,2,0,0,4,0\] 

In [6]:
list = np.array([1,2,0,0,4,0])
indexes = list.nonzero()
indexes

(array([0, 1, 4]),)

#### 7. Stwórz macierz 3x3x3 z losowymi wartościami

In [7]:
np.random.rand(3,3,3)

array([[[0.19784429, 0.39090387, 0.93356186],
        [0.34843722, 0.54357386, 0.82797259],
        [0.90443775, 0.18713521, 0.53572464]],

       [[0.80722113, 0.61426751, 0.74589459],
        [0.31822864, 0.76063731, 0.14893597],
        [0.28724412, 0.4818887 , 0.4557274 ]],

       [[0.5093807 , 0.24559012, 0.20091612],
        [0.46416538, 0.93676806, 0.48558859],
        [0.59510839, 0.80797892, 0.09219246]]])

#### 8. Stwórz macierz 10x10 wypełnioną losowymi wartościami i znajdź wartość min oraz max

In [8]:
m = np.random.rand(10,10)
mmax = m.max()
mmin = m.min()
print(mmax, mmin)
m

0.9863942219440586 0.0027416811645398775


array([[0.83668364, 0.9032442 , 0.64704262, 0.76608342, 0.45312509,
        0.77658819, 0.58270702, 0.83224857, 0.76404693, 0.62012427],
       [0.4794036 , 0.19131914, 0.21200628, 0.69370794, 0.01220015,
        0.56403117, 0.0230675 , 0.88280699, 0.92650085, 0.69801302],
       [0.70937651, 0.64674646, 0.00274168, 0.23830323, 0.01705141,
        0.93800603, 0.59257593, 0.43649563, 0.97720066, 0.58766546],
       [0.58751252, 0.17608632, 0.26470453, 0.9099884 , 0.82878533,
        0.05160882, 0.39715003, 0.07047028, 0.53505301, 0.28246983],
       [0.47966463, 0.6903519 , 0.12224537, 0.9118811 , 0.0514958 ,
        0.70022359, 0.97608975, 0.06920679, 0.69607225, 0.78957584],
       [0.05826577, 0.88954419, 0.69053002, 0.91695508, 0.82570455,
        0.09989886, 0.43441463, 0.38230111, 0.00288475, 0.29989042],
       [0.10021313, 0.74199771, 0.1701294 , 0.78239302, 0.25974137,
        0.80731306, 0.70052837, 0.52876169, 0.08954867, 0.74315536],
       [0.17279845, 0.2090025 , 0.3392657

#### 9. Stwórz losowy wektor 30-tu elementów i znajdź średnią wartość wektora

In [9]:
n = np.random.rand(30)
avg = n.mean()
avg

0.5198274347382564

#### 10. Stwórz macierz 2D, z jedynkami na brzegach oraz zerami w środku

In [10]:
def magic(m):
  m[1:-1,1:-1] = 0
  return m

m = np.ones((7,6))
print(magic(m))

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 11. Wymnóż macierz 5x3 przez macierz 3x2 (wynikowa macierz 5x2)

In [11]:
m1 = np.random.rand(5,3)
m2 = np.random.rand(3,2)
m3 = m1.dot(m2)
m3.shape

(5, 2)

#### 12. Mając wektor wartości od 0 do 9, przefiltruj elementy wektora by zostawić jedynie te, spełniające warunek (x > 2) & (x < 5)

In [12]:
x = np.arange(10)
x1 = x > 2
x2 = x < 5
x[x1&x2]


array([3, 4])

#### 13. Przefiltruj wektor array listą x, aby zostawić jedynie elementy niebędące w liście x

In [0]:
x = [4, 5, 6]
array = np.arange(10)

In [14]:
result = np.isin(array,x)
result = np.invert(result)
array = array[result]
array

array([0, 1, 2, 3, 7, 8, 9])

#### 14. Stwórz funkcję, realizującą funkcję logistyczną f(x) = 1 / (1 + exp(-x))

In [15]:
def logistic_function(x):
    fx = 1/(1 + np.exp(-x))
    return fx

print(logistic_function(7))

0.9990889488055994
